language: haskell
install: "cabal install --only-dependencies --force-reinstalls --enable-tests"
before_script: "sudo apt-get update; sudo apt-get install libxen-dev"
script: "cabal configure --enable-tests && cabal build && cabal test"
