language: haskell
install: "cabal update && cabal install --only-dependencies --force-reinstalls --enable-tests"
before_script: "sudo apt-get install libxen-dev"
script: "cabal configure && cabal build"
