# Before install are required because there is a bug in base 4.5.0 (GHC 7.4.1) with popCount in Data.Bits
before_install:
    - "sudo sh -c 'echo deb http://pl.archive.ubuntu.com/ubuntu/ quantal universe >> /etc/apt/sources.list'"
    - "sudo apt-get update"
    - "sudo apt-get install --only-upgrade -qq -t quantal ghc"
language: haskell
before_script: "sudo apt-get install libxen-dev"
script: "cabal configure && cabal build"
